"""accounts-config.yaml assembly.

SLZ does not enumerate accounts in CFN — accounts are created via Control Tower
Account Factory (LogArchive, Audit) or hand-created (SharedServices, Central
Backup, Network). We synthesize from SLZ readme intent + LZA UC mandatory list.

Email addresses are emitted as `{{ ... }}` replacement tokens so reviewer can
fill via `replacements-config.yaml` without editing accounts-config directly.
"""
from __future__ import annotations

from typing import Any

from ..common import Coverage, OUT_DIR, write_yaml
from ..profile import (
    ACCELERATOR_PREFIX,
    HOME_REGION,
    MANDATORY_ACCOUNTS,
    WORKLOAD_ACCOUNTS,
)


def build_accounts_config() -> Coverage:
    cov = Coverage()

    mandatory = []
    for name, ou, purpose in MANDATORY_ACCOUNTS:
        mandatory.append({
            "name": name,
            "description": purpose,
            "email": f"{{{{ {name}Email }}}}",
            "organizationalUnit": ou,
        })
        cov.map("(synthesized)", name, f"mandatoryAccounts[{name}]")

    workload = []
    for name, ou, purpose in WORKLOAD_ACCOUNTS:
        workload.append({
            "name": name,
            "description": purpose,
            "email": f"{{{{ {name}Email }}}}",
            "organizationalUnit": ou,
        })
        cov.map("(synthesized)", name, f"workloadAccounts[{name}]")

    accounts_config = {
        "mandatoryAccounts": mandatory,
        "workloadAccounts": workload,
    }
    header = (
        "Generated by converter. Mandatory accounts follow LZA convention;\n"
        "workload accounts inferred from SLZ readme (SharedServices, CentralBackup,\n"
        "Network — see readme Installation Steps 4, 5, 6). Emails are Jinja tokens\n"
        "resolved via replacements-config.yaml; reviewer must populate real\n"
        "distribution-list addresses (SLZ readme step 8 requires unique emails)."
    )
    write_yaml(OUT_DIR / "accounts-config.yaml", accounts_config, header=header)
    return cov


def build_replacements_config() -> Coverage:
    """Emit replacements-config.yaml using V2 schema (SSM-path-backed).

    LZA loads global replacements from SSM parameters in the management account
    in HOME_REGION. Reviewer must pre-create these SSM parameters before pipeline
    execution — the accompanying `bootstrap-ssm-params.sh` script does this.
    """
    cov = Coverage()
    # LZA V2 replacement types:
    #   type=String  → inline `value`, no `path`
    #   type=Number  → inline `value`, no `path`
    #   type=SSM     → `path` to SSM Parameter Store entry
    # Emit inline String/Number values so no SSM pre-population needed;
    # bootstrap script optional (reviewer keeps for token-rotation workflows).
    tokens: list[tuple[str, str, Any, str]] = [
        ("AcceleratorPrefix", "String", ACCELERATOR_PREFIX,
         "Prefix applied to all LZA-owned resources"),
        ("HomeRegion", "String", HOME_REGION, "SLZ home region"),
        ("TransitGatewayASN", "Number", 65001, "TGW BGP ASN (private range)"),
    ]
    for name, _ou, _p in MANDATORY_ACCOUNTS + WORKLOAD_ACCOUNTS:
        tokens.append((f"{name}Email", "String", f"TODO-{name.lower()}@example.com",
                       f"Distribution list email for {name} account"))
    globals_block = []
    for key, ptype, value, _desc in tokens:
        globals_block.append({
            "key": key,
            "type": ptype,
            "value": value,
        })
        cov.map("(synthesized)", key, f"globalReplacements[] type={ptype} value={value!r}")

    cfg = {"globalReplacements": globals_block}
    header = (
        "LZA V2 replacements — inline String/Number values. Reviewer must\n"
        "replace TODO-*@example.com email placeholders before deploy.\n"
        "AcceleratorPrefix + HomeRegion are profile-specific defaults."
    )
    write_yaml(OUT_DIR / "replacements-config.yaml", cfg, header=header)
    return cov
