"""customizations-config.yaml assembly.

[GEN] mapper contract; per-domain contributors register CFN passthrough entries here.
Domain-independent aggregator — each mapper appends its passthrough needs, then this
module writes the single customizations-config.yaml at end of pipeline.

For now: seed with the org-domain AI-opt-out CFN passthrough (only known blocker).
Later domains extend `CUSTOMIZATIONS_QUEUE` before final write.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from ..common import Coverage, OUT_DIR, write_yaml
from ..profile import ACCELERATOR_PREFIX, AI_OPTOUT_TARGET, HOME_REGION


CUSTOMIZATIONS_QUEUE: list[dict[str, Any]] = []


def register_file_passthrough(stem: str, source_file: str, note: str) -> None:
    """Register a whole SLZ CFN template for verbatim customizations passthrough."""
    CUSTOMIZATIONS_QUEUE.append(
        {
            "name": f"{ACCELERATOR_PREFIX}-{stem}",
            "template": f"cloudformation/{stem}.yaml",
            "runOrder": 5,
            "terminationProtection": False,
            "deploymentTargets": {"accounts": ["Audit"]},
            "regions": [HOME_REGION],
            "_note": (
                f"Copy source SLZ template `{source_file}` into "
                f"config/cloudformation/{stem}.yaml. {note}"
            ),
        }
    )


def register_ssm_dhmc() -> None:
    """SSM Default Host Management Configuration — no first-class LZA UC field.

    Enable via CFN custom resource wrapping ssm:UpdateServiceSetting API call.
    Applied at every managed account × home region.
    """
    CUSTOMIZATIONS_QUEUE.append(
        {
            "name": f"{ACCELERATOR_PREFIX}-ssm-default-host-management",
            "template": "cloudformation/ssm-default-host-management.yaml",
            "runOrder": 10,
            "terminationProtection": False,
            "deploymentTargets": {"organizationalUnits": ["Root"]},
            "regions": [HOME_REGION],
            "_note": (
                "Hand-author CFN template with a custom resource that calls "
                "ssm:UpdateServiceSetting with SettingId "
                "'/ssm/managed-instance/default-ec2-instance-management-role' "
                "value 'AWSSystemsManagerDefaultEC2InstanceManagementRole'. "
                "Replaces SLZ Custom::SSMDefaultHostManagement from "
                "lz-account-baseline.yaml."
            ),
        }
    )


def register_ai_optout(policy_body_relpath: str, policy_name: str) -> None:
    CUSTOMIZATIONS_QUEUE.append(
        {
            "name": f"{ACCELERATOR_PREFIX}-ai-services-optout",
            "template": "cloudformation/ai-services-optout.yaml",
            "runOrder": 1,
            "terminationProtection": False,
            "deploymentTargets": {"organizationalUnits": ["Root"]},
            "regions": [HOME_REGION],
            "_note": (
                f"Wrap AWS::Organizations::Policy Type=AISERVICES_OPT_OUT_POLICY "
                f"with Content loaded from {policy_body_relpath}, "
                f"TargetIds set to Root OU id, Name={ACCELERATOR_PREFIX}-{policy_name}."
            ),
        }
    )


def build_customizations_config(cov: Coverage) -> None:
    if not CUSTOMIZATIONS_QUEUE:
        cov.map("customizations", "queue", "empty — no passthrough needed")
        return
    cfg = {
        "customizations": {
            "cloudFormationStacks": [
                {k: v for k, v in item.items() if not k.startswith("_")}
                for item in CUSTOMIZATIONS_QUEUE
            ],
        }
    }
    header = (
        "Generated by converter (customizations aggregator).\n"
        "Passthrough entries for SLZ resources with no first-class LZA UC field.\n"
        "Each entry references a hand-authored CFN template under cloudformation/;\n"
        "see corresponding notes in reports/customizations.md."
    )
    write_yaml(OUT_DIR / "customizations-config.yaml", cfg, header=header)
    # Detailed notes go to a companion report
    notes_path = Path(OUT_DIR / "customizations.notes.md")
    lines = ["# Customizations passthrough — reviewer notes", ""]
    for item in CUSTOMIZATIONS_QUEUE:
        lines.append(f"## {item['name']}")
        lines.append("")
        lines.append(item.get("_note", ""))
        lines.append("")
    notes_path.write_text("\n".join(lines))
    cov.map("customizations", "queue", f"{len(CUSTOMIZATIONS_QUEUE)} passthrough entries")
