"""Global-config mapper — assembles global-config.yaml from profile constants +
security-domain deferrals + Control Tower baseline defaults.

Unlike other domain mappers this one is largely synthetic (no dedicated SLZ CFN
file); SLZ leaves CloudTrail/Config to Control Tower and only defines Session
Manager preferences via the account-baseline custom resource.
"""
from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from ..common import Coverage, OUT_DIR, write_yaml
from ..profile import (
    ENABLED_REGIONS,
    HOME_REGION,
    MANAGEMENT_ACCOUNT_ACCESS_ROLE,
)


def _load_deferrals() -> list[dict[str, Any]]:
    p = Path(OUT_DIR / "_deferrals/global.json")
    if not p.exists():
        return []
    return json.loads(p.read_text())


def build_global_config() -> Coverage:
    cov = Coverage()
    deferrals = _load_deferrals()

    session_manager: dict[str, Any] = {
        "sendToCloudWatchLogs": True,
        "sendToS3": True,
        "excludeRegions": [],
        "excludeAccounts": [],
        "lifecycleRules": [],
        "attachPolicyToIamRoles": [],
    }
    for d in deferrals:
        sm = d.get("sessionManager")
        if sm:
            # Only overwrite keys the deferral actually carries values for
            for k, v in sm.items():
                if v is not None and k in ("sendToCloudWatchLogs", "sendToS3",
                                            "excludeRegions", "excludeAccounts",
                                            "lifecycleRules", "attachPolicyToIamRoles"):
                    session_manager[k] = v
            cov.map("(deferral)", "sessionManager", "logging.sessionManager")

    global_config: dict[str, Any] = {
        "homeRegion": HOME_REGION,
        "enabledRegions": ENABLED_REGIONS,
        "managementAccountAccessRole": MANAGEMENT_ACCOUNT_ACCESS_ROLE,
        "cloudwatchLogRetentionInDays": 365,
        "terminationProtection": True,
        "controlTower": {
            "enable": True,
        },
        "logging": {
            "account": "LogArchive",
            "cloudtrail": {
                "enable": False,
                "organizationTrail": False,
            },
            "sessionManager": session_manager,
            "cloudwatchLogs": {
                "enable": True,
            },
        },
        "tags": [
            {"key": "CreatedBy", "value": "SecureLandingZone"},
        ],
    }
    cov.map("(synthesized)", "homeRegion", HOME_REGION)
    cov.map("(synthesized)", "controlTower.enable", "true (LZA-with-CT per SLZ)")
    cov.map("(synthesized)", "logging.cloudtrail",
            "disabled (Control Tower manages org trail)")

    header = (
        "Generated by converter L1 (global domain). Largely synthesized.\n"
        "SLZ delegates CloudTrail/Config to Control Tower; LZA-with-CT mode\n"
        "leaves logging.cloudtrail.enable=false. sessionManager values come\n"
        "from security-domain deferral (SSM session prefs custom resource)."
    )
    write_yaml(OUT_DIR / "global-config.yaml", global_config, header=header)
    return cov
