"""IAM-domain mapper — IdC permission sets → iam-config.yaml identityCenter."""
from __future__ import annotations

from typing import Any

from ..common import (
    Coverage,
    OUT_DIR,
    SLZ_CFN,
    load_cfn,
    resolve_ref,
    resource_iter,
    write_yaml,
)
from ..profile import (
    IAM_SOURCES,
    IDENTITY_CENTER_DELEGATED_ADMIN,
    IDENTITY_CENTER_NAME,
)


def _permission_set(props: dict[str, Any], tpl: dict[str, Any]) -> dict[str, Any]:
    name = resolve_ref(props.get("Name"), tpl)
    description = resolve_ref(props.get("Description"), tpl)
    session_duration = props.get("SessionDuration")
    managed = props.get("ManagedPolicies") or []
    # Strip "arn:aws:iam::aws:policy/" prefix → LZA expects awsManaged names.
    aws_managed = [
        p.rsplit("/", 1)[-1] if isinstance(p, str) and p.startswith("arn:aws:iam::aws:policy/") else p
        for p in managed
    ]
    entry: dict[str, Any] = {
        "name": name,
        "policies": {"awsManaged": aws_managed},
    }
    if description:
        entry["description"] = description
    if session_duration and isinstance(session_duration, str):
        # e.g. 'PT8H' — LZA takes minutes (integer). Parse ISO-8601 duration lazily:
        # PT<n>H → n*60; leave unmapped hint if unrecognised.
        if session_duration.startswith("PT") and session_duration.endswith("H"):
            try:
                entry["sessionDuration"] = int(session_duration[2:-1]) * 60
            except ValueError:
                pass
    return entry


def build_iam_config() -> Coverage:
    cov = Coverage()
    permission_sets: list[dict[str, Any]] = []

    for key, src in IAM_SOURCES.items():
        tpl = load_cfn(SLZ_CFN / src)
        for lid, res in resource_iter(tpl):
            rtype = res.get("Type", "")
            if rtype == "AWS::SSO::PermissionSet":
                entry = _permission_set(res.get("Properties", {}), tpl)
                permission_sets.append(entry)
                cov.map(src, lid,
                        f"identityCenter.identityCenterPermissionSets[{entry['name']}]")
            else:
                cov.unmap(src, lid, f"unhandled resource type {rtype}")

    iam_config: dict[str, Any] = {
        "providers": [],
        "policySets": [],
        "roleSets": [],
        "groupSets": [],
        "userSets": [],
        "identityCenter": {
            "name": IDENTITY_CENTER_NAME,
            "identityCenterPermissionSets": permission_sets,
            # SLZ does not create IdC assignments in CFN (done post-deploy in console).
            # Emitting empty list — reviewer wires assignments in L2 pass.
            "identityCenterAssignments": [],
        },
    }
    if IDENTITY_CENTER_DELEGATED_ADMIN:
        iam_config["identityCenter"]["delegatedAdminAccount"] = (
            IDENTITY_CENTER_DELEGATED_ADMIN
        )
    header = (
        "Generated by converter L1 (iam domain).\n"
        "Source: sample-thailand-secure-lz/cloudformation/lz-iam-idc-permissionsets.json.\n"
        "identityCenterAssignments is EMPTY — SLZ handles principal→permissionSet\n"
        "assignments post-deploy via console; reviewer must add per-account\n"
        "assignments manually or wire in L2 pass."
    )
    write_yaml(OUT_DIR / "iam-config.yaml", iam_config, header=header)
    return cov
